/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BoardGame;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * 
 * @author Nathan Watkins
 */
import javax.swing.*;

public class BoardGameUI extends JFrame {
    
    String player1Name = "Player 1";
    String player2Name = "Player 2";
    String player3Name = "Player 3";
    String player4Name = "Player 4";

    Player player1 = new Player(player1Name, 0);
    
    /**
     * Creates new form NewJFrame
     */
    public BoardGameUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        gameBoard = new Board();
        sidePanelContainer = new javax.swing.JPanel();
        arrowsContainer = new javax.swing.JPanel();
        arrowDown = new javax.swing.JButton();
        arrowUp = new javax.swing.JButton();
        arrowLeft = new javax.swing.JButton();
        arrowRight = new javax.swing.JButton();
        roundNumberGraphic = new javax.swing.JLabel();
        playerTurnGraphic = new javax.swing.JLabel();
        helpButton = new javax.swing.JButton();
        rollDiceButton = new javax.swing.JButton();
        Player1Resources = new javax.swing.JPanel();
        player1ResourceTitle = new javax.swing.JLabel();
        player1Satisfaction = new javax.swing.JLabel();
        player1Knowledge = new javax.swing.JLabel();
        player1Asphalt = new javax.swing.JLabel();
        player1Resources = new javax.swing.JLabel();
        Player2Resources = new javax.swing.JPanel();
        player2ResourceTitle = new javax.swing.JLabel();
        player2Satisfaction = new javax.swing.JLabel();
        player2Knowledge = new javax.swing.JLabel();
        player2Asphalt = new javax.swing.JLabel();
        player2Resources = new javax.swing.JLabel();
        Player3Resources = new javax.swing.JPanel();
        player3ResourceTitle = new javax.swing.JLabel();
        player3Satisfaction = new javax.swing.JLabel();
        player3Knowledge = new javax.swing.JLabel();
        player3Asphalt = new javax.swing.JLabel();
        player3Resources = new javax.swing.JLabel();
        Player4Resources = new javax.swing.JPanel();
        player4ResourceTitle = new javax.swing.JLabel();
        player4Satisfaction = new javax.swing.JLabel();
        player4Knowledge = new javax.swing.JLabel();
        player4Asphalt = new javax.swing.JLabel();
        player4Resources = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sidePanelContainer.setLayout(null);

        arrowsContainer.setName(""); // NOI18N
        arrowsContainer.setLayout(null);

        arrowDown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrows/ArrowDown.png"))); // NOI18N
        arrowDown.setBorder(null);
        arrowDown.setContentAreaFilled(false);
        arrowDown.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        arrowDown.setFocusPainted(false);
        arrowsContainer.add(arrowDown);
        arrowDown.setBounds(45, 46, 46, 46);

        arrowUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrows/ArrowUp.png"))); // NOI18N
        arrowUp.setBorder(null);
        arrowUp.setContentAreaFilled(false);
        arrowUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        arrowUp.setFocusPainted(false);
        arrowsContainer.add(arrowUp);
        arrowUp.setBounds(45, 1, 46, 46);

        arrowLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrows/ArrowLeft.png"))); // NOI18N
        arrowLeft.setBorder(null);
        arrowLeft.setContentAreaFilled(false);
        arrowLeft.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        arrowLeft.setFocusPainted(false);
        arrowsContainer.add(arrowLeft);
        arrowLeft.setBounds(0, 46, 46, 46);

        arrowRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrows/ArrowRight.png"))); // NOI18N
        arrowRight.setBorder(null);
        arrowRight.setContentAreaFilled(false);
        arrowRight.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        arrowRight.setFocusPainted(false);
        arrowsContainer.add(arrowRight);
        arrowRight.setBounds(90, 46, 46, 46);
        
        sidePanelContainer.add(arrowsContainer);
        arrowsContainer.setBounds(10, 405, 138, 92);

        roundNumberGraphic.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        roundNumberGraphic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Round.png"))); // NOI18N
        roundNumberGraphic.setText("Round 1");
        roundNumberGraphic.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sidePanelContainer.add(roundNumberGraphic);
        roundNumberGraphic.setBounds(251, 0, 122, 57);

        playerTurnGraphic.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        playerTurnGraphic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PlayerTurn.png"))); // NOI18N
        playerTurnGraphic.setText("     " + player2Name + "'s Turn");
        playerTurnGraphic.setToolTipText("");
        playerTurnGraphic.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sidePanelContainer.add(playerTurnGraphic);
        playerTurnGraphic.setBounds(0, 0, 241, 57);

        helpButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Help.png"))); // NOI18N
        helpButton.setBorder(null);
        helpButton.setContentAreaFilled(false);
        helpButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sidePanelContainer.add(helpButton);
        helpButton.setBounds(330, 380, 37, 37);

        rollDiceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/RollDiceButton.png"))); // NOI18N
        rollDiceButton.setBorder(null);
        rollDiceButton.setContentAreaFilled(false);
        rollDiceButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rollDiceButton.setFocusPainted(false);
        sidePanelContainer.add(rollDiceButton);
        rollDiceButton.setBounds(170, 450, 192, 47);

        Player1Resources.setLayout(null);

        player1ResourceTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        player1ResourceTitle.setText(player1Name);
        Player1Resources.add(player1ResourceTitle);
        player1ResourceTitle.setBounds(10, -3, 350, 30);

        player1Satisfaction.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        player1Satisfaction.setText("999");
        Player1Resources.add(player1Satisfaction);
        player1Satisfaction.setBounds(310, 23, 60, 40);

        player1Knowledge.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        player1Knowledge.setText("999");
        Player1Resources.add(player1Knowledge);
        player1Knowledge.setBounds(185, 23, 60, 40);

        player1Asphalt.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        player1Asphalt.setText("999");
        Player1Resources.add(player1Asphalt);
        player1Asphalt.setBounds(60, 23, 60, 40);

        player1Resources.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Resources.png"))); // NOI18N
        Player1Resources.add(player1Resources);
        player1Resources.setBounds(0, 0, 373, 74);

        sidePanelContainer.add(Player1Resources);
        Player1Resources.setBounds(0, 62, 373, 74);

        Player2Resources.setLayout(null);

        player2ResourceTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        player2ResourceTitle.setText(player2Name);
        Player2Resources.add(player2ResourceTitle);
        player2ResourceTitle.setBounds(10, -3, 350, 30);

        player2Satisfaction.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        player2Satisfaction.setText("999");
        Player2Resources.add(player2Satisfaction);
        player2Satisfaction.setBounds(310, 23, 60, 40);

        player2Knowledge.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        player2Knowledge.setText("999");
        Player2Resources.add(player2Knowledge);
        player2Knowledge.setBounds(185, 23, 60, 40);

        player2Asphalt.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        player2Asphalt.setText("999");
        Player2Resources.add(player2Asphalt);
        player2Asphalt.setBounds(60, 23, 60, 40);

        player2Resources.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Resources.png"))); // NOI18N
        Player2Resources.add(player2Resources);
        player2Resources.setBounds(0, 0, 373, 74);

        sidePanelContainer.add(Player2Resources);
        Player2Resources.setBounds(0, 141, 373, 74);

        Player3Resources.setLayout(null);

        player3ResourceTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        player3ResourceTitle.setText(player3Name);
        Player3Resources.add(player3ResourceTitle);
        player3ResourceTitle.setBounds(10, -3, 350, 30);

        player3Satisfaction.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        player3Satisfaction.setText("999");
        Player3Resources.add(player3Satisfaction);
        player3Satisfaction.setBounds(310, 23, 60, 40);

        player3Knowledge.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        player3Knowledge.setText("999");
        Player3Resources.add(player3Knowledge);
        player3Knowledge.setBounds(185, 23, 60, 40);

        player3Asphalt.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        player3Asphalt.setText("999");
        Player3Resources.add(player3Asphalt);
        player3Asphalt.setBounds(60, 23, 60, 40);

        player3Resources.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Resources.png"))); // NOI18N
        Player3Resources.add(player3Resources);
        player3Resources.setBounds(0, 0, 373, 74);

        sidePanelContainer.add(Player3Resources);
        Player3Resources.setBounds(0, 220, 373, 74);

        Player4Resources.setLayout(null);

        player4ResourceTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        player4ResourceTitle.setText(player4Name);
        Player4Resources.add(player4ResourceTitle);
        player4ResourceTitle.setBounds(10, -3, 350, 30);

        player4Satisfaction.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        player4Satisfaction.setText("999");
        Player4Resources.add(player4Satisfaction);
        player4Satisfaction.setBounds(310, 23, 60, 40);

        player4Knowledge.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        player4Knowledge.setText("999");
        Player4Resources.add(player4Knowledge);
        player4Knowledge.setBounds(185, 23, 60, 40);

        player4Asphalt.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        player4Asphalt.setText("999");
        Player4Resources.add(player4Asphalt);
        player4Asphalt.setBounds(60, 23, 60, 40);

        player4Resources.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Resources.png"))); // NOI18N
        Player4Resources.add(player4Resources);
        player4Resources.setBounds(0, 0, 373, 74);

        sidePanelContainer.add(Player4Resources);
        Player4Resources.setBounds(0, 299, 373, 74);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gameBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(sidePanelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(gameBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sidePanelContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        setSize(new java.awt.Dimension(915, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BoardGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BoardGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BoardGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BoardGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            BoardGame game = new BoardGame();
            game.setVisible(true);
            game.setTitle("CSC2058 Potholes Board Game");
        });

        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Player1Resources;
    private javax.swing.JPanel Player2Resources;
    private javax.swing.JPanel Player3Resources;
    private javax.swing.JPanel Player4Resources;
    private javax.swing.JButton arrowDown;
    private javax.swing.JButton arrowLeft;
    private javax.swing.JButton arrowRight;
    private javax.swing.JButton arrowUp;
    private javax.swing.JPanel arrowsContainer;
    private Board gameBoard;
    private javax.swing.JButton helpButton;
    private javax.swing.JLabel player1Asphalt;
    private javax.swing.JLabel player1Knowledge;
    private javax.swing.JLabel player1ResourceTitle;
    private javax.swing.JLabel player1Resources;
    private javax.swing.JLabel player1Satisfaction;
    private javax.swing.JLabel player2Asphalt;
    private javax.swing.JLabel player2Knowledge;
    private javax.swing.JLabel player2ResourceTitle;
    private javax.swing.JLabel player2Resources;
    private javax.swing.JLabel player2Satisfaction;
    private javax.swing.JLabel player3Asphalt;
    private javax.swing.JLabel player3Knowledge;
    private javax.swing.JLabel player3ResourceTitle;
    private javax.swing.JLabel player3Resources;
    private javax.swing.JLabel player3Satisfaction;
    private javax.swing.JLabel player4Asphalt;
    private javax.swing.JLabel player4Knowledge;
    private javax.swing.JLabel player4ResourceTitle;
    private javax.swing.JLabel player4Resources;
    private javax.swing.JLabel player4Satisfaction;
    private javax.swing.JLabel playerTurnGraphic;
    private javax.swing.JButton rollDiceButton;
    private javax.swing.JLabel roundNumberGraphic;
    private javax.swing.JPanel sidePanelContainer;
    // End of variables declaration//GEN-END:variables
}
